version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: saas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: SaaS
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_backend
    environment:
      DB_HOST: mysql
      DB_USER: saas_user
      DB_PASSWORD: saas_password123
      DB_NAME: SaaS
      DB_PORT: 3306
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: saas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
